version: '3'
services:
  mysql_master:
    image: mysql:8
    env_file:
      - ./config/master/master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4306:3306
    volumes:
      - ./config/master/conf/master.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./data/master/data:/var/lib/mysql
    networks:
      - mysql_replication

  mysql_slave:
    image: mysql:8
    env_file:
      - ./config/slave/slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5306:3306
    depends_on:
      - mysql_master
    volumes:
      - ./config/slave/conf/slave.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./data/slave/data:/var/lib/mysql
    networks:
      - mysql_replication

networks:
  mysql_replication: